_L = 
{
	"There are two types of goto: long and short. Short move is performed if goto and label are located inside same block (has one parent). This type of move preserves execution history and script continues afterward. In other cases long move is performed, which clears execution history. Long move case is perfect if you are jumping on script start, but if you move inside loop, you must use another move to leave it, otherwise thread will stop with success message.": 
	{"ru": "Есть два типа goto: длинные и короткие. Короткое перемещение выполняется, если goto и метка расположены внутри одного и того же блока (имеют одного родителя). Этот тип перемещения сохраняет историю выполнения и скрипт продолжается впоследствии. В других случаях выполняется длинное перемещение, которое очищает историю выполнения скрипта. Вариант с длинным перемещением идеально подходит, если вы перемещаетесь в начало скрипта, но если вы перемещаетесь в цикл или в условие, то вы должны использовать еще одно действие перемещения, чтобы выйти из цикла, иначе поток остановится с успешным сообщением."},
	"Enable Flash": {"ru": "Использовать Флеш"},
	"Disable webrtc and canvas": {"ru": "Отключить webrtc и canvas"},

	"Force UTF-8 Encoding": {"ru": "Преобразовывать все страницы в UTF-8"},
	"Proxies reconnect": {"ru": "Восстановление соединения"},
	"Number of frames to skip in run mode": {"ru": "Пропуск кадров в рабочем режиме."},

	"Empty string or 0 means, that value wont be changed. \"Enable Flash\" and \"Disable webrtc and canvas\" options will restart browser process and thereby reset all settings(proxies, headers, etc), so the best place to use this action is thread start. If you want to change settings for every thread, it is better to use settings tab.": {"ru": "Пустая строка или 0 означает, что значение изменяться не будут. \"Использовать Флеш\" и \"Отключить webrtc и canvas\" перезапустят браузер и таким образом обнулят остальные настройки(прокси, заголовки, и т.д.), так что лучшее место для этого действия - начало работы потока. Если вы хотите поменять настройки для всех потоков, то лучше воспользоваться вкладкой настройки."},

	

	"Scroll to search for image": {"ru": "Прокрутка для поиска изображения"},
	"How well the image must fit. 100 - exactly fits, 0 - does not fit at all.": {"ru": "Насколько хорошо изображение должно подходить. 100 - точно подходит, 0 - не подходит совсем."},
	"Additional parameters.": {"ru": "Дополнительные параметры."},
	"Image data as base64": {"ru": "Данные изображения в формате base64."},
	"Variable to save screenshot as base64": {"ru": "Переменная для сохранения результата как base64."},
	"Wait for element.": {"ru": "Ждать появления элемента."},
	"Fail thread if element not found.": {"ru": "Остановить поток, если элемент не найден."},
	"Use \"Set Variable\" action to create variable.": {"ru": "Используйте действие \"Установить переменную\" для создания переменной."},
	"You can create resource with \"+ Create New Resource\" button which is located in the panel to the right.": {"ru": "Вы можете создать ресурс с помощью кнопки \"+ Создать новый ресурс\", которая расположена на панели справа."},
	"By default script will stop after resource is finished. You can use this option to complete not the entire script, but only the thread.": {"ru": "По умолчанию скрипт останавливается после завершения ресурса. Вы можете использовать эту опцию для остановки не всего скрипта, а только потока."},
	"Next": {"ru": "Дальше"},
	"found": {"ru": "найдено"},
	"Select resource": {"ru": "Выбрать ресурс"},
	"Element selector": {"ru": "Селектор элемента"},
	"Insert existing variable": {"ru": "Вставить существующую переменную"},
	"Create value in visual constructor": {"ru": "Создать значение в конструкторе"},
	"Load from file, user input, database": {"ru": "Взять из файла, поля для ввода или базы"},
	"Insert variable": {"ru": "Из переменной"},
	"Remove bookmark": {"ru": "Удалить закладку"},
	"Your recent actions": {"ru": "Последние действия"},
	"History": {"ru": "История"},
	"Bookmarks": {"ru": "Закладки"},
	"Drag actions here": {"ru": "Перетаскивайте действия сюда"},
	"Data exchange can only be performed with global variables or resources.": {"ru": "Обмен данными может быть осуществлен только с помощью глобальных переменных или ресурсов."},
	"Global: ": {"ru": "Глобальная: "},
	"Record list": {"ru": "Список записей"},
	"Remove this filter?": {"ru": "Удалить этот фильтр?"},
	"Not empty": {"ru": "Не пустое"},
	"Is empty": {"ru": "Пустое"},
	"Contains": {"ru": "Содержит"},
	"Equals": {"ru": "Равно"},
	"Not equals": {"ru": "Не равно"},
	"Is true": {"ru": "Истина"},
	"Is false": {"ru": "Ложь"},
	"Earlier then": {"ru": "Раньше чем"},
	"Later then": {"ru": "Позже чем"},
	"Same year": {"ru": "В том же году"},
	"Same month": {"ru": "В тот же месяц"},
	"Same day": {"ru": "В тот же день"},
	"Same hour": {"ru": "В тот же час"},
	"Action history is clean": {"ru": "История действий пуста"},
	"Return to main screen": {"ru": "Вернуться на главный экран"},
	

	"Table": {"ru": "Таблица"},
	"Field": {"ru": "Поле"},
	"Filter type": {"ru": "Тип фильтра"},
	"Add filter": {"ru": "Добавить фильтр"},
	"Take new or old resource during current resource request.": {"ru": "Брать новый ресурс или использовать старый при данном запросе ресурса."},
	"Restrict all popups. You can restrict specific popup with Request Mask Deny action.": {"ru": "Запретить все всплывающие окна. Запретить конкретные окна можно с помощью действия Запретить запрос"},
	"Restrict all downloads. You can restrict specific download with Request Mask Deny action.": {"ru": "Запретить загрузку файлов. Запретить конкретные загрузки можно с помощью действия Запретить запрос"},
	"Allow all popups. Revokes Allow popup action.": {"ru": "Разрешить все всплывающие окна. Отменяет действие Запретить всплывающие окна"},
	"Allow all downloads. Revokes Allow downloads action.": {"ru": "Разрешить все загрузки. Отменяет действие Запретить загрузку файлов"},
	"Tweak speed and other parameters for mouse move.": {"ru": "Настроить скорость и другие параметры для перемещения мыши."},
	"Speed": {"ru": "Скорость"},
	"Gravity": {"ru": "Притяжение"},
	"Deviation": {"ru": "Отклонение"},
	"Use 'Timeout' action to set default timeout.": {"ru": "Используйте действие 'Таймаут' чтобы установить максимальное время ожидания по умолчанию."},
	"default": {"ru": "дефолт"},
	"Select Label": {"ru": "Выберите Метку"},
	"No label found. Create one with Set label action.": {"ru": "Меток не найдено. Ее можно создать с помощью действия Установить метку."},
	"Default": {"ru": "По умолчанию"},
	"seconds": {"ru": "секунд"},
	"Maximum time to perform an action.": {"ru": "Максимальное время выполнения задания"},
	"Target url": {"ru": "Применять к урл"},
	"Target tab number": {"ru": "Применять к вкладке с номером"},
	"Dont restart thread.": {"ru": "Не перезапускать поток.","en": "Don't restart thread."},
	"Finish script instantly.": {"ru": "Завершить скрипт мгновенно."},
	"Load cookies from browser.": {"ru": "Загрузить куки из браузера."},
	"Load cookies from http client.": {"ru": "Загрузить куки из http клиента."},
	"Close browser.": {"ru": "Закрыть браузер."},
	"Open browser.": {"ru": "Открыть браузер."},
	"Restart process": {"ru": "Перезапуск процесса"},
	"Variable To save file name": {"ru": "Переменная для сохранения пути к файлу"},
	"Wait for the end of the current download.": {"ru": "Ждать окончания текущей загрузки"},
	"Add As Base64 Data": {"ru": "Добавить как данные base64"},
	"Additional Parameters": {"ru": "Дополнительные параметры"},
	"Content Type": {"ru": "Тип содержимого"},
	"Encoding": {"ru": "Кодировка"},
	"Request Parameter Value": {"ru": "Значение параметра запроса"},
	"Request Parameter Name": {"ru": "Имя параметра запроса"},
	"Use these buttons to fill POST data": {"ru": "Используйте эти кнопки, чтобы заполнить данные запроса"},
	"Add As File": {"ru": "Добавить Как Файл"},
	"Method": {"ru": "Метод"},
	"Drag x position": {"ru": "X Координата"},
	"Drop y position": {"ru": "Y Координата"},
	"Trying to interrupt ...": {"ru": "Пытаюсь прервать ..."},
	"Interrupt": {"ru": "Прервать"},
	"Executing Action": {"ru": "Выполняется действие"},
	"Tab Index": {"ru": "Номер Вкладки"},
	"Disable mouse emulation.": {"ru": "Отключить эмуляцию мыши."},
	"Disable mouse and keyboard emulation.": {"ru": "Отключить эмуляцию мыши и клавиатуры."},
	"Server url. Can be blank": {"ru": "Url сервера. Может быть пустым"},
	"Immediately End Script": {"ru": "Немедленно Прервать Скрипт"},
	"Use Template": {"ru": "Использовать Шаблон"},
	"Replace all occurrences of one string to another": {"ru": "Заменить все вхождения одной строки на другую"},
	"Resolves template to variable. Can contain {{Resources}} and [[VARIABLES]] and spintax {hi|hello}.": {"ru": "Генерирует строку по шаблону. Шаблон может содержать {{Ресурсы}} и [[ПЕРЕМЕННЫЕ]] и спинтакс {вариант 1|вариант 2}"},
	"Replace From": {"ru": "Заменить Из"},
	"Original String": {"ru": "Оригинальная Строка"},
	"Replace To": {"ru": "Заменить На"},
	"Allowed Chars": {"ru": "Разрешенные Символы"},
	"Result String Length": {"ru": "Длина Генерируемой Строки"},
	"Minimum Value": {"ru": "Минимальное Значение"},
	"Maximum Value": {"ru": "Максимальное Значение"},
	"Additional processing. Use this option if you want to load template from file or variable.": {"ru": "Дополнительная обработка. Используйте эту настройку, чтобы грузить шаблон из файла или переменной."},
	
	"If error will occur during ignore error block, it will be ignored and execution will continue on next after block instruction.": {"ru": "Если ошибка произойдет во время блока игнорирования ошибок, то ошибка будет проигнорирована, а выполнение продолжится на следующем после блока действии."},
	"Increase variable value": {"ru": "На сколько увеличить переменную"},
	"This means [[VARIABLE]] = [[VARIABLE]] + num": {"ru": "Это означает [[VARIABLE]] = [[VARIABLE]] + num"},
	"Variable Name": {"ru": "Имя Переменной"},
	"Wait full page load after this action": {"ru": "Ждать полной загрузки страницы после этого действия"},
	"Toggle target. Apply this action only to specific url or to specific tab.": {"ru": "Применить это действие только к определенным урл или определенным вкладкам."},

	"Wait for full page load": {"ru": "Ждать полной загрузки"},
	"Wait until full page load.": {"ru": "Ждать пока страница не будет полностью загружена."},

	"Prompt user input result": {"ru": "Результат ввода"},
	"Http auth login": {"ru": "HTTP Аутентификация логин"},
	"Http auth password": {"ru": "HTTP Аутентификация пароль"},

	"STRING": {"ru": "СТРОКА"},
	"INT": {"ru": "ЧИСЛО"},
	"EXPRESSION": {"ru": "ВЫРАЖЕНИЕ"},
	
	"Confirm Changes": {"ru": "Подтвердить Изменения"},
	"Replace old value": {"ru": "Заменить старое значение"},
	"with new one": {"ru": "новым выражением"},
	"OK": {"ru": "ОК"},
	"Enter Value": {"ru": "Введите значение"},
	"CANCEL": {"ru": "ОТМЕНА"},
	
	

	"ACCEPT": {"ru": "ПРИНЯТЬ"},
	"value1": {"ru": "значение1"},
	"value2": {"ru": "значение2"},
	"expression": {"ru": "выражение"},
	"value": {"ru": "значение"},
	"string": {"ru": "строка"},
	"first": {"ru": "первый"},
	"second": {"ru": "второй"},
	"index1": {"ru": "индекс1"},
	"index2": {"ru": "индекс2"},
	"string part": {"ru": "часть строки"},
	"replace from": {"ru": "заменить из"},
	"replace to": {"ru": "заменить на"},
	"regexp": {"ru": "рег выражение"},
	"array": {"ru": "массив"},
	"min": {"ru": "мин"},
	"max": {"ru": "макс"},
	"element": {"ru": "элемент"},
	"number1": {"ru": "число1"},
	"number2": {"ru": "число2"},
	"separator": {"ru": "разделитель"},
	"index": {"ru": "индекс"},
	"array1": {"ru": "массив1"},
	"array2": {"ru": "массив2"},
	"alphabet": {"ru": "словарь"},
	"length": {"ru": "длина"},
  	"Returns true if value1 equal value2, otherwise false": {"ru": "Возвращает true, если значение1 равно значению2, в противном случае возвращает false"},
	"Returns true if value1 is less than value2, otherwise false": {"ru": "Возвращает true, если значение1 меньше значения2, в противном случае возвращает false"},
	"Returns true if value1 is not greater than value2, otherwise false": {"ru": "Возвращает true, если значение1 не больше значения2, в противном случае возвращает false"},
	"Returns true if value1 is greater than value2, otherwise false": {"ru": "Возвращает true, если значение1 больше значения2, в противном случае возвращает false"},
	"Returns true if value1 is not less than value2, otherwise false": {"ru": "Возвращает true, если значение1 не меньше значения2, в противном случае возвращает false"},
    "Value": {"ru": "Значение"},  
    "result": {"ru": "результат"},
    "Code": {"ru": "Код"},
	"and": {"ru": "и"},
	"or": {"ru": "или"},
	"not": {"ru": "не"},
	"if": {"ru": "если"},
	"concat": {"ru": "соединить строки"},
	"length": {"ru": "длина"},
	"contains": {"ru": "содержит"},
	"substring": {"ru": "подстрока"},
	"search": {"ru": "поиск"},
	"replace": {"ru": "заменить"},
	"split with string": {"ru": "разделить строкой"},
	"split with regexp": {"ru": "разделить рег выражением"},
	"matches": {"ru": "совпадает"},
	"scan": {"ru": "поиск"},
	"random number": {"ru": "случайное число"},
	"random string": {"ru": "случайная строка"},
	"random alphabet": {"ru": "случайный словарь"},
	"empty array": {"ru": "пустой массив"},
	"create array": {"ru": "создать массив"},
	"array push": {"ru": "добавить в массив"},
	"array concat": {"ru": "соединить массивы"},
	"array insert": {"ru": "вставить в массив"},
	"array length": {"ru": "длина массива"},
	"array get index": {"ru": "получить элемент"},
	"array join": {"ru": "массив в строку"},
	"subarray": {"ru": "подмассив"},
	"custom": {"ru": "произвольный код"},
	"Returns true if value1 is true and value2 is true, otherwise false": {"ru": "Возвращает true, если значение1 и значение2 равно true, в противном случае false"},
	"Returns true if value1 is true or value2 is true, otherwise false": {"ru": "Возвращает true, если значение1 или значение2 равно true, в противном случае false"},
	"Returns true if value is false and false if value is true": {"ru": "Возвращает true, если значение равно false, и false если значение равно true"},
	"Returns value1 if expression true and value2 otherwise": {"ru": "Возвращает значение1 если выражение равно true и значение2 в противном случае"},
	"Add one string to another": {"ru": "Соединить две строки"},
	"Returns string length": {"ru": "Длина строки"},
	"Check if one string contains another": {"ru": "Проверить, содержит ли одна строка вторую"},
	"Takes substring from a given string. First param - string, second - first index, third - second index": {"ru": "Получает подстроку из заданной строки. Первый параметр - строка, второй - первый индекс, третий - второй индекс"},
	"Searches for string part inside string, if found returns found index, otherwise returns -1": {"ru": "Поиски части строки внутри строки, если строка присутствует, возвращает найденный индекс, в противном случае возвращает -1"},
	"Replace all occurrences of one string with another": {"ru": "Заменить все вхождения одной строки другой"},
	"Splits string with defined separator. Returns array of strings": {"ru": "Разделяет строку другой строкой. Возвращает массив строк"},
	"Splits string with defined regexp. Returns array of strings": {"ru": "Разделяет строку регулярным выражением. Возвращает массив строк"},
	"Returns true if string matches given regexp": {"ru": "Возвращает true, если строка подходит под регулярное выражение"},
	"Generate random number": {"ru": "Случайное число"},
	"Generate random string": {"ru": "Случайная строка"},
	"Generate random string, with given alphabet. Alphabet is just a string, for example, if alphabet is 01 action will generate random binary number": {"ru": "Генерация случайной строки, с заданным алфавитом. Алфавит это просто строка, например, если алфавит является 01, то действие будет генерировать случайные двоичные числа"},
	"Creates empty array": {"ru": "Создать пустой массив"},
	"Creates array with single element": {"ru": "Создать массив с одним элементом"},
	"Add value to the end of array": {"ru": "Добавить элемент в конец массива"},
	"Concat several arrays": {"ru": "Объединить 2 массива"},
	"Add value to specific place of array": {"ru": "Добавить элемент в заданное место массива"},
	"Get array length": {"ru": "Получить длину массива"},
	"Get element from array by index": {"ru": "Получить элемент массива с заданным индексом"},
	"Join array of strings with defined separator": {"ru": "Преобразовать массив в строку с заданным разделителем"},
	"Takes subarray from a given array. First param - array, second - first index, third - second index": {"ru": "Получает подмассив из заданного массива. Первый параметр - массив, второй - первый индекс, третий - второй индекс"},
	"Adds numbers": {"ru": "Прибавить числа"},
	"Substracts numbers": {"ru": "Вычесть числа"},
	"Multiply numbers": {"ru": "Умножить числа"},
	"Divide numbers": {"ru": "Разделить числа"},
	"Execute custom code": {"ru": "Выполнить произвольный код"},

	"Use this action if last captcha was solved wrong.": {"ru": "Используйте это действие, если прошлая капча была решена неправильно"},
	"Timeout Type": {"ru": "Тип таймаута"},
	"Timeout in milliseconds": {"ru": "Таймаут в миллисекундах"},
	"Set Timeout": {"ru": "Установить Таймаут"},
	"Foreach Array": {"ru": "Foreach массив"},
	"Variables To Save Links" : {"ru": "Переменные со ссылками"},
	"Parse email and get link list. Put variables in following format to Variables To Save Links: LINK1,LINK2,LINK3" : {"ru": "Парсить почту и сохранить список ссылок. Поместите переменные в следующем формате: LINK1,LINK2,LINK3"},
	"Use action 'Search First', if you want to get only one message.": {"ru": "Используйте действи 'Найти письмо' если хотите получить только одно сообщение."},
	"If captcha appear" : {"ru": "При появлении капчи"},
	"Reuse Resource" : {"ru": "Повторное использование"},
	"Don't end application if not exists" : {"ru": "Не прерывать приложение"},
	"Load specific url" : {"ru": "Загрузить URL"},
	"Get current url" : {"ru": "Получить Текущий URL"},
	"Save page html to variable" : {"ru": "Сохранить код страницы в переменной"},
	"Browser" : {"ru": "Браузер"},
	"Type text on page. For example, put email in input field" : {"ru": "Вводить текст на странице. Например, вставить электронную почту в поле ввода"},
	"Change browser size" : {"ru": "Изменить размер браузера"},
	"Set proxy" : {"ru": "Установить прокси"},
	"Execute javascript" : {"ru": "Выполнить яваскрипт"},
	"Clear all browser data" : {"ru": "Очистить все данные браузера"},
	"Set open file dialog result" : {"ru": "Установить результат диалога Открыть Файл"},
	"Scroll to position" : {"ru": "Прокрутка к координатам"},
	"Render screen part to variable as png base64 encoded" : {"ru": "Скриншот части экрана в формате PNG в base64 кодировке"},
	"Stop loop." : {"ru": "Остановить цикл"},
	"Continue" : {"ru": "Continue"},

	"File Write" : {"ru": "Запись в файл"},
	"File Read" : {"ru": "Читать из файла"},
	"Threads" : {"ru": "Потоки"},
	"Success Number" : {"ru": "Максимальное число удачных запусков"},
	"Fail Number" : {"ru": "Максимальное число неудачных запусков"},
	"Waiters" : {"ru": "Ожидание"},
	/*"Wait until browser will load url" : {"ru": "Подождите, пока браузер не будет загружать URL"},
	"Wait address bar will contain url" : {"ru": "Подождите, пока адресная строка будет содержать URL"},
	"Wait until specific text will be present on page" : {"ru": "Подождите, пока конкретный текст будет присутствовать на странице"},
	"Wait until specific css selector will return non empty result" : {"ru": "Подождите, пока селектор конкретного CSS вернет непустой результат"},
	"Sleep for a specific time" : {"ru": "Сон в течение определенного времени"},*/
	"Script logic" : {"ru": "Логика скрипта"},
	/*"Execute conditional actions" : {"ru": "Выполнить условные действия"},
	"Execute while loop" : {"ru": "Выполнить во время цикла"},
	"Execute for loop" : {"ru": "Выполнить цикл"},
	"Stop loop" : {"ru": "Остановить цикл"},
	"Start next loop iteration" : {"ru": "Начало следующей итерации цикла"},
	"Finish script with success result" : {"ru": "Завершить сценарий с результатом успеха"},
	"Finish script with fail result" : {"ru": "Завершить сценарий с результатом неудачу"},
	"Sets or creates variable" : {"ru": "Устанавливает или создает переменную"},
	"Call function" : {"ru": "Вызов функции"},*/
	"Tools" : {"ru": "Инструменты"},
	/*"Output string to log" : {"ru": "Выходная строка для входа"},
	"Save result" : {"ru": "Сохранить результат"},
	"Execute custom code" : {"ru": "Выполнить пользовательский код"},
	"Write to file" : {"ru": "Запись в файл"},
	"Read from file" : {"ru": "Чтение из файла"},
	"Base64 encode or decode" : {"ru": "Base64 кодирования и декодирования"},
	"Set global variable" : {"ru": "Установить глобальную переменную"},
	"Get global variable" : {"ru": "Получить глобальную переменную"},
	"Parse line like this 'a1:a2:a3' and save to variables" : {"ru": "Анализировать линии, как это 'a1: a2: a3' и сохранить в переменных"},*/
	"Network" : {"ru": "Сеть"},
	/*"Set HTTP Headers, like user agent, accept language, etc" : {"ru": "Установить HTTP-заголовки, как агент пользователя, принимают язык и т.д."},
	"Save all cookies to variable" : {"ru": "Сохранить все куки для переменной"},
	"Restore cookies, which is saved with Save Cookies command" : {"ru": "Восстановление куки, которая сохраняется с помощью команды Сохранить Cookies"},
	"Allow save loaded url content to cache" : {"ru": "Разрешить сохранить загруженный URL-адрес содержимого в кэше"},
	"Deny save loaded url content to cache" : {"ru": "Запретить сохранить загруженный URL-адрес содержимого в кэше"},
	"Allow load url, which matching mask" : {"ru": "Разрешить нагрузки URL, который соответствующий маска"},
	"Deny load url, which matching mask" : {"ru": "Запретить нагрузки URL, который соответствующего маске"},
	"Clear loaded cache data" : {"ru": "Очистить данные, загруженные кэш"},
	"Clear cache masks" : {"ru": "Очистить кэш маски"},
	"Get url load status" : {"ru": "Получить статус Загрузить URL"},
	"Check if url is loaded" : {"ru": "Проверьте, если URL загружается"},
	"Get base64 encoded cached page" : {"ru": "Получить base64 закодирован кэшированной страницы"},*/
	"Email" : {"ru": "Почта"},
	/*"Configure email settings" : {"ru": "Настройка электронной почты"},
	"Configure email proxy" : {"ru": "Настройка электронной почты прокси"},
	"Get messages length" : {"ru": "Получить длину сообщения"},
	"Search for first message" : {"ru": "Поиск первого сообщения"},
	"Search for all messages" : {"ru": "Поиск всех сообщений"},
	"Pull message" : {"ru": "Прицепные сообщение"},
	*/"Script properties" : {"ru": "Cвойства"},
	/*"Set thread number" : {"ru": "Установить номер нити"},
	"Set success number. When script will be executed successfully 'success number' of times, application will stop" : {"ru": "Набор номера успеха. Когда сценарий будет успешно выполнен 'число успеха' раз, приложение остановится"},
	"Set fail number. When script will fail 'fail number' of times, application will stop" : {"ru": "Установить неудачу номер. Когда сценарий потерпит неудачу "сбой" номер раз, приложение остановится"},*/
	"Http Client" : {"ru": "HTTP-клиент"},
	/*"Set proxy for http client" : {"ru": "Установка прокси для HTTP клиента"},
	"Reset http client" : {"ru": "Сброс клиента HTTP"},
	"Make GET request" : {"ru": "Сделать запрос GET"},
	"Make POST request" : {"ru": "Сделать запрос POST"},
	"Download to file" : {"ru": "Загрузить в файл"},
	"Get http client current url" : {"ru": "Получить HTTP-клиент текущий URL"},
	"Get http client request result" : {"ru": "Получить HTTP результат запроса клиента"},
	"Get http client request status" : {"ru": "Получить статус HTTP запроса клиента"},
	"Get http client header" : {"ru": "Получить заголовок HTTP клиента"},
	"Set http client header" : {"ru": "заголовок клиента HTTP Set"},
	"Clear http client request headers" : {"ru": "Четкие заголовки запросов HTTP-клиент"},
	"Save all cookies to variable" : {"ru": "Сохранить все куки для переменной"},
	"Restore cookies, which is saved with Save Cookies command" : {"ru": "Восстановление куки, которая сохраняется с помощью команды Сохранить Cookies"},
	"Fail if error during http request" : {"ru": "Потерпеть неудачу, если ошибка во время запроса HTTP"},
	"Check if error" : {"ru": "Проверьте, если ошибка"},
	"Get last error string" : {"ru": "Получить последнюю строку ошибки"},
	"Execute xpath query and get result xml" : {"ru": "Выполнить XPATH запрос и получить результат XML"},
	"Execute xpath query and get result text" : {"ru": "Выполнить XPATH запрос и получить результирующий текст"},
	"Execute xpath query and get result count" : {"ru": "Выполнить XPATH запрос и получить подсчет результата"},
	"Execute xpath query and check if exists" : {"ru": "Выполнить XPATH запрос и проверить, существует ли"}
*/
	"Ok" : {"ru": "Ок"},
	"Cancel" : {"ru": "Отмена"},
	"Start next loop iteration." : {"ru" : "Начать следующую итерацию."},
	"Finish thread with success result." : {"ru" : "Завершить поток с успешным результатом."},
	"Finish thread with fail result." : {"ru" : "Завершить поток с неуспешным результатом."},
	"Finish whole script." : {"ru" : "Завершить весь скрипт."},
	"Break depth. If blank will break current loop, if integer will break with desired depth, if string will break until desired function." : {"ru" : "Глубина."},
	"Wait address bar will contain url" : {"ru": "Ждать пока адресная строка будет содержать URL"},
	"Select Resource" : {"ru": "Выбрать ресурс"},
	"No resources found." : {"ru": "Не найдено ресурсов."},
	"Select Variable" : {"ru": "Выбор переменной"},
	"No variables found." : {"ru": "Переменных не найдено."},
	"Select Function" : {"ru": "Выберите функцию"},
	"No functions found." : {"ru": "Функций не найдено."},
	"Only Execute" : {"ru": "Только Выполнить"},
	"Only Add" : {"ru": "Только Добавить"},
	"Execute And Add" : {"ru": "Выполнить и Добавить"},
	"Url to load" : {"ru": "Url сайта"},
	"Break depth" : {"ru": "Глубина"},
	"Fail Message" : {"ru": "Сообщение об ошибке"},
	"Success Message" : {"ru": "Сообщение об успехе"},

	"Custom Code" : {"ru": "Пользовательский код"},
	"Wait until browser will load url" : {"ru": "Подождите, пока браузер не загрузит Url"},
	"Wait until specific text will be present on page" : {"ru": "Ждать, пока конкретный текст будет присутствовать на странице"},
	"Wait until specific css selector will return non empty result" : {"ru": "Ждать, пока css селектор вернет непустой результат"},
	"Function name" : {"ru": "Название функции"},
	"Header Name" : {"ru": "Имя заголовка"},
	"Header Value" : {"ru": "Значение заголовка"},
	"Captcha picture data encoded in base64" : {"ru": "Данные изображения в base64"},
	"Solve Method" : {"ru": "Метод решения"},
	"Antigate/Rucaptcha/2captcha/DBC Key. Can be blank" : {"ru": "Ключ Антигейт/Рукапча/2капча/dbc. Может быть пустым"},
	"DBC Login:Password. Can be blank" : {"ru": "DBC Логин:Пароль. Может быть пустым"},
	"Variable To Save Result" : {"ru": "Переменная, в которую сохранять результат"},
	"Variable To Save" : {"ru": "Переменная, в которую сохранить результат"},
	"Script Text" : {"ru": "Текст сценария"},
	"Line" : {"ru": "Строка"},
	"Variables To Save Result" : {"ru": "Переменные, в которые сохранять результат"},
	"Parse line which contains list of varibales. Example, parse line <i>email@gmail.com:mypass1</i> to variables USERNAME and PASSWORD." : {"ru": "Парсить строку, которая содержит список переменных. Пример, строка <i>email@gmail.com:mypass1</i> в переменные USERNAME и PASSWORD."},
	"Put variables in following format to Variables List field: USERNAME,PASSWORD" : {"ru": "Поместите переменные в следующем формате: USERNAME,PASSWORD"},
	"Clear all browser data." : {"ru": "Очистить все данные браузера."},
	"File path to set as result of open file dialog" : {"ru": "Путь к файлу, который будет результатом вызова диалога открытия файла"},
	"Url" : {"ru": "Url"},
	"Cookies" : {"ru": "Cookies"},
	"Scroll x position" : {"ru": "X координата"},
	"Scroll y position" : {"ru": "Y координата"},
	"Width" : {"ru": "Ширина"},
	"Height" : {"ru": "Высота"},
	"Variable to save as base64 png" : {"ru": "Переменная, в которую сохранять в формате base64 PNG"},
	"Match" : {"ru": "Маска"},

	"Add page content to cache if url is matching. For example *.json - caches all json" : {"ru": "Добавить содержимое страницы в кэш, если URL соответствует маске. Например * .json - кэширует все JSON запросы"},
	"Do not add page content to cache if url is matching." : {"ru": "Не добавлять содержимое страницы в кэш, если URL соответствует маске."},
	"Clear all cache masks." : {"ru": "Очистить все маски кэша."},
	"Allow load url if url is matching. By default every url is loaded" : {"ru": "Разрешить загрузку URL, если URL соответствует маске. По умолчанию каждый URL загружается"},
	"Deny load url if url is matching. For example *.png disables loading png images." : {"ru": "Запретить загрузки URL, если URL соответствует маске. Например *.png отключает загрузку изображений в формате PNG."},
	"Clear all requests masks." : {"ru": "Очистить все маски запросов."},
	"Clear all cache masks." : {"ru": "Очистить все маски кэша."},
	"Clear info about all loaded urls." : {"ru": "Очистить информацию о всех загруженных URL."},
	"Encode in base64" : {"ru": "Кодировать в base64"},
	"After execution variale will hold cached page content which matching url." : {"ru": "После выполнения переменная будет держать кэшированное содержание страницы."},
	"Result Data" : {"ru": "Данные"},
	"Result Placeholder" : {"ru": "Номер результата"},
	"File path" : {"ru": "Путь к файлу"},
	"Encode or decode" : {"ru": "Шифровать или расшифровывать"},
	"Group" : {"ru": "Группа"},
	"Name" : {"ru": "Имя"},
	"Value" : {"ru": "Значение"},
	"Global variables are availabe during whole script run." : {"ru": "Глобальные переменные доступны в течение работы приложения."},
	"Imap Server Host" : {"ru": "Imap сервер"},
	"Port" : {"ru": "Порт"},
	"Username. Can be blank" : {"ru": "Имя пользователя. Может быть пустым"},
	"Password. Can be blank" : {"ru": "Пароль. Может быть пустым"},
	"Encryption" : {"ru": "Шифрование"},
	"Inbox name" : {"ru": "Имя папки"},
	"Proxy String" : {"ru": "Прокси"},
	"Function Name" : {"ru": "Название функции"},
	"Proxy Type" : {"ru": "Тип прокси"},
	"Proxy Login. Can be blank." : {"ru": "Прокси Войти. Может быть пустым."},
	"Proxy password. Can be blank." : {"ru": "Пароль прокси-сервера. Может быть пустым."},
	"Sender Query" : {"ru": "Отправитель Письма"},
	"Subject Query" : {"ru": "Тема Письма"},
	"Body Query" : {"ru": "Текст Письма"},
	"Proxy Login. Can be blank." : {"ru": "Прокси Логин. Может быть пустым."},
	"Proxy password. Can be blank." : {"ru": "Пароль Прокси. Может быть пустым."},
	"Clear all http client data." : {"ru": "Очистить все данные HTTP-клиента."},
	"File Path" : {"ru": "Путь к файлу"},
	"Follow redirects" : {"ru": "Следовать переадресациям"},
	"Post Data" : {"ru": "Данные Запроса"},
	"Name" : {"ru": "Имя"},
	"Value" : {"ru": "Значение"},
	"Add" : {"ru": "Добавить"},
	"Is Multipart" : {"ru": "Is Multipart"},
	"Header Name" : {"ru": "Имя заголовка"},
	"Clear all headers." : {"ru": "Очистить все заголовки."},
	"Cookies" : {"ru": "Cookies"},
	"Xpath Query" : {"ru": "Xpath Запрос"},
	"Fail on error" : {"ru": "Завершать работу после ошибки"},
	"If expression" : {"ru": "If Выражение"},
	"Add else block" : {"ru": "Добавить else блок"},
	"While expression" : {"ru": "While выражение"},
	"For from value" : {"ru": "От"},
	"For to value" : {"ru": "До"},
	"Sleep to value in milliseconds" : {"ru": "Время сна в миллисекундах. От"},
	"Sleep from value in milliseconds" : {"ru": "Время сна в миллисекундах. До"},
	"Sleep value in milliseconds" : {"ru": "Время сна в миллисекундах"},
	"Sleep random time" : {"ru": "Спать случайное время"},
	"Name of variable" : {"ru": "Имя переменной"},
	"Value of variable" : {"ru": "Значение переменной"},
	"Script Text" : {"ru": "Текст сценария"},
	"Click on element." : {"ru": "Нажать на элемент."},
	"Move mouse pointer on element." : {"ru": "Навести курсор на элемент."},
	"Move mouse pointer and click on element." : {"ru": "Навести курсор и нажать на элемент."},
	"Clear edit. Works only on edit." : {"ru": "Очистить поле. Работает только на текстовых полях."},
	"Text to type" : {"ru": "Текст для ввода"},
	"Interval in milliseconds" : {"ru": "Интервал в миллисекундах"},
	"Also check if visible on a screen" : {"ru": "Проверять, виден ли элемент на экране"},
	"Check if element exists." : {"ru": "Проверять, существует ли элемент."},
	"Style To Check" : {"ru": "Стиль"},
	"Get element style. Use \"display\" to check if element is visible" : {"ru": "Получить стиль элемента. Используйте display, чтобы проверить, если элемент виден"},
	"Check cehckbox. Works only on checkboxes." : {"ru": "Состояние чекбокса. Работает только на чекбоксах."},
	"Wait until page state will be \"complete\"." : {"ru": "Ждать, пока состояние страницы не будет complete."},
	"Wait while matching query element exists on page." : {"ru": "Подождите, пока соответствующий элемент появится на странице."},
	"Scroll to element." : {"ru": "Прокрутить до элемента."},

	"Set String" : {"ru": "Строка"},
	"Set combobox value to desired string. Works only on comboboxes." : {"ru": "Установить значение выпадающего списка. Работает только на выпадающих списках."},
	"Set Index" : {"ru": "Индекс"},
	"Set combobox index to desired int. Works only on comboboxes." : {"ru": "Установить индекс значения выпадающего списка. Работает только на выпадающих списках."},
	"Set combobox index to random int. Works only on comboboxes." : {"ru": "Выбрать случайное значение из выпадающего списка. Работает только на выпадающих списках."},
	"Attribute Name" : {"ru": "Имя атрибута"},

	"Get element attribute." : {"ru": "Получить атрибут элемента."},
	"Attribute Value" : {"ru": "Значение атрибута"},
	"Set element attribute." : {"ru": "Установить атрибут элемента."},
	
	"Get elements number matching query." : {"ru": "Получить количество элементов соответствующее запросу."},
	"Foreach element, which matching query." : {"ru": "Выполнить для каждого элемента, соответствующего запросу."},
	"Move x position" : {"ru": "Х координата"},
	"Move y position" : {"ru": "У координата"},
	"Click x position" : {"ru": "Х координата"},
	"Click y position" : {"ru": "У координата"},
	"Thread number" : {"ru": "Количество потоков"},
	"Fail number" : {"ru": "Количество допустимых ошибок"},
	"Success number" : {"ru": "Количество успешных выполнений"},
	"Move and click x position" : {"ru": "Х координата"},
	"Move and click y position" : {"ru": "Y координата"},
	"Function name" :{"ru": "Имя функции"},
	"Data to Log" :{"ru": "Данные для вывода"},
	"Data" :{"ru": "Данные"},
	"Message Id":{"ru": "Идентификатор сообщения"},
	"Use self variable, which is point to selected element.":{"ru": "Используйте переменную self, которая указывает на выбранный элемент."},
	"Start Loop to use this function" :{"ru": "Начните цикл, чтобы использовать эту функцию"},
	"What to search?" :{"ru": "Что искать?"},
	"Execute javascript on every page load in browser" :{"ru": "Выполнять яваскрипт при каждой загрузке страницы в браузере"},

}


function tr(key)
{
	if(typeof(key) == "undefined")
	{

		var all = $(".tr")
		
		for(var i = 0;i< all.length;i++)
		{
			var el = $(all[i])
			if(typeof(el.attr("tr")) == "undefined" || el.attr("tr") != "true" )
			{
				el.html(tr(el.html()))
				el.attr("tr","true")
			}
		}

		all = $(".trtitle")
		
		for(var i = 0;i< all.length;i++)
		{
			var el = $(all[i])
			if(typeof(el.attr("trtitle")) == "undefined" || el.attr("tr") != "true" )
			{
				el.attr("title",tr(el.attr("title")))
				el.attr("trtitle","true")
			}
		}

		var all = $("*[placeholder]")
		
		for(var i = 0;i< all.length;i++)
		{
			var el = $(all[i])
			if(typeof(el.attr("tr")) == "undefined" || el.attr("tr") != "true" )
			{
				el.attr("placeholder",tr(el.attr("placeholder")))
				el.attr("tr","true")
			}
		}

		
		
		return;
	}

	
	if(typeof(_K) == "undefined" || _K == "en")
		return key;
	if(key in _L)
	{

		if(_K in _L[key])
		{
			return _L[key][_K]
		}
	}
	return key;
}